In [2]:
import torch

inputs = torch.tensor(
    [
        [0.43, 0.15, 0.89],  # Your      (x^1)
        [0.55, 0.87, 0.66],  # journey   (x^2)
        [0.57, 0.85, 0.64],  # starts    (x^3)
        [0.22, 0.58, 0.33],  # with      (x^4)
        [0.77, 0.25, 0.10],  # one       (x^5)
        [0.05, 0.80, 0.55],  # step      (x^6)
    ]
)


In [4]:
input_1=inputs[0]
input_1


tensor([0.4300, 0.1500, 0.8900])

In [5]:
input_query=inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [6]:
torch.dot(input_query,input_1)

tensor(0.9544)

In [7]:
for ele in inputs[0]:
    print(ele)

tensor(0.4300)
tensor(0.1500)
tensor(0.8900)


In [9]:

for index,ele in enumerate(inputs[0]):
    print(inputs[0][index])

tensor(0.4300)
tensor(0.1500)
tensor(0.8900)


In [12]:
res=0
i=0
for index,ele in enumerate(inputs[i]):
    res+=(inputs[i][index]*input_query[index])
print(res)

tensor(0.9544)


In [14]:
query=inputs[1]#2nd i/p token is the query token
attn_scores_2=torch.empty(inputs.shape[0])
for i,x_i in enumerate(inputs):
    attn_scores_2[i]=torch.dot(x_i,input_query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [19]:
attn_weights_2=torch.softmax(attn_scores_2,dim=0)

In [20]:
query=inputs[1]
context_vec2=torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    print(f"{attn_weights_2[i]}-->{inputs[i]}")
    #context_vec2+=attn_weights_2[i]*x_i
#print(context_vec2)

0.13854756951332092-->tensor([0.4300, 0.1500, 0.8900])
0.2378913015127182-->tensor([0.5500, 0.8700, 0.6600])
0.23327402770519257-->tensor([0.5700, 0.8500, 0.6400])
0.12399158626794815-->tensor([0.2200, 0.5800, 0.3300])
0.10818186402320862-->tensor([0.7700, 0.2500, 0.1000])
0.15811361372470856-->tensor([0.0500, 0.8000, 0.5500])


In [21]:
query=inputs[1]
context_vec2=torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    context_vec2+=attn_weights_2[i]*x_i
print(context_vec2)

tensor([0.4419, 0.6515, 0.5683])


generalising simple self attention mech

In [23]:
attn_scores=torch.empty(6,6)
for i,x_i in enumerate(inputs):
    for j,x_j in enumerate(inputs):
        attn_scores[i][j]=torch.dot(x_i,x_j)
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [25]:
#in pytorch for loops are slower as compared to matrix multiplications
attn_scores=inputs@inputs.T
attn_scores

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [26]:
attn_weights=torch.softmax(attn_scores,dim=1)

In [27]:
all_context_vecs=attn_weights@inputs
all_context_vecs

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

Implementing self attention weights step by step

Computing the attention weights step by step

In [35]:
x_2=inputs[1]
d_in=inputs.shape[1]
d_out=2

tensor([0.5500, 0.8700, 0.6600])

In [31]:
torch.manual_seed(123)
W_query=torch.nn.Parameter(torch.rand(d_in,d_out))
W_key=torch.nn.Parameter(torch.rand(d_in,d_out))
W_value=torch.nn.Parameter(torch.rand(d_in,d_out))
#we use torch.nn.Parameter to make sure that the matrices or tensors
#are trainable

In [34]:
query_2=x_2@W_query
query_2#the same query vector is reused everywhere
#for key and value vectors every vector has diff key and value vectors

tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)

In [39]:
keys=inputs@W_key
value=inputs@W_value
keys

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]], grad_fn=<MmBackward0>)

In [40]:
keys_2=keys[1]
attn_score_22=torch.dot(keys_2,query_2)

In [42]:
attn_scores_2= query_2@keys.T
attn_scores_2

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
       grad_fn=<SqueezeBackward4>)

In [44]:
d_k=keys.shape[1]
attn_weights_2=torch.softmax(attn_scores_2/d_k**0.5,dim=-1)

tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
       grad_fn=<SoftmaxBackward0>)

In [47]:
context_vec_2=attn_weights_2@value
context_vec_2

tensor([0.3069, 0.8188], grad_fn=<SqueezeBackward4>)

Generalising for all vectors

In [49]:
import torch
import torch.nn as nn

class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        # x: (seq_len, d_in)
        queries = x @ self.W_query
        keys    = x @ self.W_key
        values  = x @ self.W_value

        attn_scores  = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / (keys.shape[-1] ** 0.5),
            dim=-1
        )

        context_vec = attn_weights @ values
        return context_vec


# Example usage
torch.manual_seed(123)

sa_v1 = SelfAttention_v1(d_in, d_out)
sa_v1(inputs)


tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)

In [50]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [51]:
import torch
import torch.nn as nn

class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        # x: (seq_len, d_in)
        queries = self.W_query(x)
        keys    = self.W_key(x)
        values  = self.W_value(x)

        attn_scores = queries @ keys.T
        d_k = keys.shape[-1]

        attn_weights = torch.softmax(
            attn_scores / (d_k ** 0.5),
            dim=-1
        )

        context_vec = attn_weights @ values
        return context_vec


# Example usage
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)

sa_v2(inputs)


tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)

3.5 Hiding Causal Attention

In [53]:
queries = sa_v2.W_query(inputs)
keys    = sa_v2.W_key(inputs)
values  = sa_v2.W_value(inputs)

attn_scores = queries @ keys.T
d_k = keys.shape[-1]

attn_weights = torch.softmax(
    attn_scores / (d_k ** 0.5),
    dim=-1
)
attn_weights

tensor([[0.1921, 0.1646, 0.1652, 0.1550, 0.1721, 0.1510],
        [0.2041, 0.1659, 0.1662, 0.1496, 0.1665, 0.1477],
        [0.2036, 0.1659, 0.1662, 0.1498, 0.1664, 0.1480],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.1661, 0.1564],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.1585],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)

In [54]:
context_length=attn_scores.shape[0]
mask_simple=torch.tril(torch.ones(context_length,context_length))
mask_simple

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [55]:
masked_simple=attn_weights*mask_simple
masked_simple
#but now the rows do not sum up to 1

tensor([[0.1921, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2041, 0.1659, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2036, 0.1659, 0.1662, 0.0000, 0.0000, 0.0000],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.0000, 0.0000],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<MulBackward0>)

In [56]:
row_sums=masked_simple.sum(dim=-1,keepdim=True)
masked_simple_norm=masked_simple/row_sums
masked_simple_norm

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<DivBackward0>)

In [57]:
###instead of doing these 4 steps u have an alternate method
###just do the masking just after receiving the attn scores and before converting to attn weights
###also mask with -inf so that when u do torch.exp it becomes 0
"""mask = torch.triu(
    torch.ones(context_length, context_length),
    diagonal=1
)

# Apply mask
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)

print(masked)
"""


Dropout masks dooes masking on top of causal masks 
This is done while training to reduce overfitting
##modern llms dont use it gpt2 used it however

In [58]:
torch.manual_seed(123)
layer=torch.nn.Dropout(0.5)


In [59]:
example=torch.ones(6,6)
example

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [60]:
layer(example)

tensor([[2., 2., 2., 2., 2., 2.],
        [0., 2., 0., 0., 0., 0.],
        [0., 0., 2., 0., 2., 0.],
        [2., 2., 0., 0., 0., 2.],
        [2., 0., 0., 0., 0., 2.],
        [0., 2., 0., 0., 0., 0.]])

#to maintain approximately the same sum in each row 
#we rescale other values by 1/1-d.r

Implementing a compact casual self attention class

In [64]:
batch=torch.stack((inputs,inputs),dim=0)
batch.shape

torch.Size([2, 6, 3])

Extending single head attention to multi head attention
We use multihead attention so that we can have various views for the same i/p vector ig

In [77]:
class MultiHeadAttentionWrapper(nn.Module):
    def __init__(self,d_in,d_out,context_length,dropout,num_head=2,qkv_bias=False):
        super().__init__()
        self.heads=nn.ModuleList([CausalAttention(d_in,d_out,context_length,dropout,qkv_bias) for _ in range(num_head)
        ])
    def forward(self,x):
        return torch.cat([head(x) for head in self.heads],dim=-1)
torch.manual_seed(123)

context_length = batch.shape[1]
d_in, d_out = 3 , 2

mha = MultiHeadAttentionWrapper(
    d_in, d_out, context_length, dropout=0.0, num_head=2
)
mha(batch)
##notice here since we call for heads using a for loop we waste a lot of time 
##even though each head is run independently
##so we will see a diff implementation to save time and utilise GPUs

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5874,  0.0058,  0.5891,  0.3257],
         [-0.6300, -0.0632,  0.6202,  0.3860],
         [-0.5675, -0.0843,  0.5478,  0.3589],
         [-0.5526, -0.0981,  0.5321,  0.3428],
         [-0.5299, -0.1081,  0.5077,  0.3493]]], grad_fn=<CatBackward0>)